name: Serval tests

on: [push]

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest]
        racket-vm: [racket,cs]
    runs-on: ${{matrix.os}}
    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      env:
        RACKET_VM: ${{matrix.racket-vm}}
      run: ./scripts/install-deps.sh
    - name: Install Serval
      run: raco pkg install --auto -i ./serval
    - name: Run Serval tests
      run: make -C test all
